### PR TITLE
Add support for Chinese encoding GB2312

### PR DESCRIPTION
**Pull request by mvorisek**

### CODE REVIEW

**Comment by mvorisek** [comment]
Fix for PHP notice warnings like:

Notice: iconv(): Wrong charset, conversion from `UTF8' to `UTF-8//TRANSLIT//IGNORE' is not allowed in ...\vendor\zbateson\mail-mime-parser\src\Stream\Helper\CharsetConverter.php on line 336

Notice: iconv(): Wrong charset, conversion from `134' to `UTF-8//TRANSLIT//IGNORE' is not allowed in ...\vendor\zbateson\mail-mime-parser\src\Stream\Helper\CharsetConverter.php on line 335

**Comment by zbateson** [comment]
Lovely, thanks for highlighting that :+1: 

Unfortunately your patch for the UTF8 bit misses something -- conversion shouldn't actually happen in that case.  I'm stripping out non-alphanumeric characters from a charset to try and match a charset in mb_list_encodings, but not stripping out non-alphanumeric chars from mb_list_encodings to test the other way around.

Could you modify your patch to only add '134' as an alias for GB2312?  I'll have to fix the underlying charset detection logic -- unless you're willing to look into that as well, but I'd prefer a separate pull request if you will :)

Thanks again!

**Comment by zbateson** [comment]
Upon further investigation this seems to be part of a list of Microsoft codes.  I found a related issue here: https://github.com/ddeboer/imap/issues/270 -- they've linked to this Microsoft page that lists the codes: https://msdn.microsoft.com/en-us/library/cc194829.aspx

I'll close this and commit a full list of aliases like they did.

**Comment by zbateson** [comment]
Hi @mvorisek -- did you copy/paste that error from your earlier post?  The line numbers match with the old version of the file, not the new one.  Also, it should be fixed... it shouldn't be calling iconv at all anymore in that situation.

I also tried changing _data/emails/m0008.txt to use "utf8" in 0.4.11 instead of "utf-8" and check if iconv is being called, and it's not for me, so I'm not sure what's happening for you without more details.

All the best

**Pull request closed without merging**
